ktor:
    application:
        modules:
            - ua.rikutou.studiobackend.ApplicationKt.module
    deployment:
        port: 8080
        host: 192.168.50.79
jwt:
  domain: "http://0.0.0.0:8080"
  audience: "jwt-audience"
  realm: "ktor sample app"
  issuer: "http://0.0.0.0:8080"
storage:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://192.168.50.100:5432/studio_backend"
  user: "studio"